### ISSUE TITLE
Generic Representation Issues

### ISSUE THREAD

**Issue by blakeembrey** [syrusakbary/snapshottest#57]
I'm trying to use this for snapshotting, but running into issues with `GenericRepr` and double quoting problems when asserting the match. I tried `master` since it appeared to have fixed this and run into a new issue, the `GenericRepr` isn't used and instead it's directly `datetime.date(...)` or `Decimal(...)`. The problem with this is that these types were never imported to start with, so I run into type issues.

Is there a reason these are representations in Python instead of a multiline string representation like in Jest? Jest only handles formatting and compares the formatted objects which makes things simpler (e.g. does this string equal the other), while the complexity of this project seems a bit higher from equality checks.

**Comment by blakeembrey** [comment]
I ended up doing a quick backwards incompatible rewrite locally to always serialize to string is much easier to work with and comprehend from my own point of view. The file snapshot util could be turned into another method or exposed differently. I found the most confusing part from the current project structure stems from a `Formatter` being used to assert and store in addition to formatting code to a string. This could be split into two separate layers so formatters are responsible for formatting _only_ while a `SnapshotMethod` could be used for assertion testing and storing results. Let me know if you'd be interested in seeing this refactor!

**Comment by jasonkuhrt** [comment]
Example:

```
E       assert stored snapshot should match the received value
E
E         > Received value does not match stored snapshot `test_parse_request_event_body_ok 1`.
E         > tests/apigateway/snapshots/snap_test_parse_request_event_body.py
E
E         - Snapshot
E         + Received
E
E         - GenericRepr(""<Model a=1 b='foobar'>"")
E         ?             -                        -
E         + GenericRepr("<Model a=1 b='foobar'>")
```

**Comment by blakeembrey** [comment]
The other reason the string representation ended up being useful is because I when I went the generic representation route it failed when testing line endings. If you serialize a multiline string with Windows `\r\n`, it will be loaded differently in Python as `\n` when using the multiline Python string `"""`. This results in the snapshot never matching.

**Comment by AlexMabry** [comment]
If this project is no longer being maintained, could you release your version?

**Comment by blakeembrey** [comment]
@AlexMabry I'll look into it, never done Python package management before. Are you using Pytest or something else? I'd only be comfortable maintaining Pytest support myself since I don't use any other testing framework.

**Comment by ygormutti** [comment]
Fixed in master by #82. cc @yourbuddyconner

**Comment by blakeembrey** [comment]
@ygormutti Looking at the code it still seems to be based on saving `GenericRepr`? That wouldn't work for any sufficiently advanced example, e.g. different line endings across OSes (https://github.com/syrusakbary/snapshottest/issues/57#issuecomment-423286432).

**Comment by ygormutti** [comment]
Can you write a test case that reproduces this line ending issue? I think this may not be an issue because:
- `GenericRepr` isn't formatted to multiline strings
- Multiline strings line endings are converted to `\n` by Python
- When opening text files Python also convert line endings to `\n`

The only scenario where I see line endings making a difference is when dealing with `bytes`. It isn't directly supported by snapshottest, so it will be wrapped inside a `GenericRepr`, which will also handle things nicely. I agree this could be improved, but IMHO that's another issue.

**Comment by ygormutti** [comment]
About serializing objects to string, I'm not sure this is a good choice because we would loose semantic diffing features implemented by test runners, like pytest. E.g. what about objects that serialize differently but are equal according to `==`?

**Comment by yourbuddyconner** [comment]
I agree that #82 should have most of these issues solved. However, if @blakeembrey can produce a test case that fails consistently with the new logic, the argument of serializing down to a string certainly does have merit. 

I'll leave this issue open for the time being pending seeing those test cases.

**Comment by ygormutti** [comment]
Some cons of storing strings instead of objects:
- GenericRepr is pretty much a way to store objects as strings and it's already implemented;
- If you want to store an object as a string other than its repr you can do it by using custom formatters;
- https://github.com/syrusakbary/snapshottest/issues/75 presents a scenario (using pytest hooks to compare complex objects) that seems harder to accomplish if we store things as strings
- it's harder to compare objects at semantically if they are stored as strings

The only pro I see is simplifying the comparison code. I think they did it that way in Jest because in JavaScript you can't override `==`.

**Comment by yourbuddyconner** [comment]
Yeah, that was my understanding of the `GenericRepr` as well.

**Comment by blakeembrey** [comment]
> I think they did it that way in Jest because in JavaScript you can't override `==`.

That doesn't really have any merit since Jest already works correctly without `==`, testing would be impossible otherwise... You instead write a function like `expect(x).toEqual(y)` that does the comparison.

**Comment by blakeembrey** [comment]
> Multiline strings line endings are converted to \n by Python
> When opening text files Python also convert line endings to \n

You're correct that it wasn't `GenericRepr`, it just presents other issues. The issue is this. But since it seems clear that the current behavior is intended I'll close this ticket.

**Comment by blakeembrey** [comment]
> E.g. what about objects that serialize differently but are equal according to `==`?

Doesn't this break with `GenericRepr`? But it works when it's handled in this library. Isn't that inconsistent? I suspect most people, like myself, want to test the snapshot hasn't changed (including types), not that the value is equal to the snapshot.

**Comment by ygormutti** [comment]
@blakeembrey your questions made me reflect and better understand why I think the current approach is better. Let me expand on that.

> That doesn't really have any merit since Jest already works correctly without ==, testing would be impossible otherwise... You instead write a function like expect(x).toEqual(y) that does the comparison.

Operator overloading is an easy way to reuse custom equality comparison in tests, but I know it's not the only one. Please, don't take that part about operator overloading as anything more than a wild guess. :sweat_smile: 

The point really is: if you want to use custom assertions, then you can't use Jest snapshots because they're always compared using line diffs. You can use custom serializers to workaround that, but you'll still be limited to line diffs and their issues. See this example:

![image](https://user-images.githubusercontent.com/114103/60564512-54eb1c80-9d36-11e9-99cb-d6de5e96c471.png)

I don't think printing binary trees in ASCII art and comparing them using a line diff is a good way to solve this problem. We can use custom assertions with snapshottest approach. As a bonus, you can opt-in to Jest-like snapshots by wrapping the object in a `PrettyDiff`. I like to think of serializing the object to code as a clever way to allow smarter assertions while avoiding writing deserializers and still allowing comparison using line diffs.

> Doesn't this break with GenericRepr? But it works when it's serialized to a type directly. Isn't that inconsistent? I suspect most people, like myself, want to test the snapshot hasn't changed (including types), not that the value is loosely equal to the snapshot.

It's the same thing with Jest. If your snapshots contains non-deterministic values, like timestamps, your tests will break (equivalent of `GenericRepr` scenario). If this happens in a lot of tests you can solve this by writing a custom serializer that doesn't prints the timestamps, making your tests pass (equivalent to custom formatter scenario). Now I see `==` is also not the point here. :|

Some people have asked for a feature that makes snapshottest ignore some fields in other issues. In my work, there are lots of cases where I need to delete fields from objects to make snapshot tests deterministic, so I think it's a common scenario to want to check if a value is loosely equal to the snapshot.

**Comment by dspacejs** [comment]
Still having issues with this on version `0.5.1`:

```
======================================================================
FAIL: test_inauthenticated_request (journal.tests.test_schema_mutations.UpdatePrimaryGoalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniel/Dev/projects/dream/server/journal/tests/test_schema_mutations.py", line 169, in test_inauthenticated_request
    self.assertMatchSnapshot(result.errors)
  File "/home/daniel/Dev/projects/dream/server/.venv/lib/python3.7/site-packages/snapshottest/unittest.py", line 105, in assert_match_snapshot
    self._snapshot.assert_match(value)
  File "/home/daniel/Dev/projects/dream/server/.venv/lib/python3.7/site-packages/snapshottest/module.py", line 225, in assert_match
    PrettyDiff(prev_snapshot, self)
  File "/home/daniel/Dev/projects/dream/server/.venv/lib/python3.7/site-packages/snapshottest/unittest.py", line 29, in assert_equals
    self.assertEqual(value, snapshot)
AssertionError: stored snapshot should match the received value

> Received value does not match stored snapshot `UpdatePrimaryGoalTests::test_inauthenticated_request 1`.
> journal/tests/snapshots/snap_test_schema_mutations.py

- Snapshot 
+ Received 
  
  [
-     GenericRepr(""GraphQLLocatedError('You do not have permission to perform this action')"")
?                 -                                                                          -
+     GenericRepr("GraphQLLocatedError('You do not have permission to perform this action')")
  ]
```

**Comment by ygormutti** [comment]
@dspacejs maybe this broken snapshot was generated in a previous (buggy) version. What happens if you delete it and update the snapshots?
