### ISSUE TITLE
Got a bug? New Fork of this project

### ISSUE THREAD

**Issue by yourbuddyconner** [syrusakbary/snapshottest#81]
Hey! If you're looking for a fix for this project, it's been inactive for about a year. I have forked it and am maintaining the codebase here: https://github.com/yourbuddyconner/pysnap

Please feel free to report issues or bugs over there!

**Comment by ygormutti** [comment]
Have you tried contacting the project members before making your mind on doing a hard fork? Even though one year is a lot of inactive time nowadays, IMHO this should be the last option. I think someone interested in maintaining it (I volunteer! You too, naturally!) getting write permission to continue this project is the best option.

Also, I've just submitted two PRs fixing some things you fixed in your fork and some big issues. If you had submitted them as PRs here I would base my changes on yours and you could integrate them right away. Now they need additional work, because there are merge conflicts. I'm working on it.

**Comment by yourbuddyconner** [comment]
@ygormutti For the record, I have sent an email to @syrusakbary, but have not received a reply. I needed a bug fix rather urgently so I decided to fix it myself as the fix had been sitting in a PR for months already. 

Happy to see there's other people who care about the library's well-being!

**Comment by ygormutti** [comment]
For that matter, we have been using snapshottest commit hashes in our `requirements.txt` and `Pipfile`s for years now, which I recognize is a bad sign regarding the library's well-being.

I'm not sure @syrusakbary checks his public email, but for sure he's an active Twitter user, his last tweet was from five days ago, so I sent him a DM.

**Comment by syrusakbary** [comment]
Sorry for the delay replying. I've been focused in a new venture and didn't have a lot of time to review PRs here.
I've made @yourbuddyconner maintainer of the project, so you can start maintaining it and cleaning it up.

**Comment by syrusakbary** [comment]
Closing the issue :)
